using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheGamemastersChronicler
{
    public static class CharacterGenerator
    {
        private static Random rand = new();

        public static Character GenerateRandomCharacter(int id = 0)
        {
            var character = new Character
            {
                character_Name = $"TestCharacter_{id}",
                character_Age = rand.Next(18, 70),
                character_Location = GetRandomLocation(),
                character_Events = new List<string>(),
                character_Notes = new List<string> { "Autogenerated for testing." },
            };

            return character;
        }

        private static string GetRandomLocation()
        {
            string[] locations = { "Terra", "Prometheus", "Barnard", "Agidda", "Lagash", "Junction", 
                "Dingir", "Kinunir", "Meshan", "Lilike", "Langelos", "Munilgan", "Lagash", "Gaea", "Kidashi"
            , "Chrysolite", "Mirabilis", "Ys", "Tewfik", "Lamarck", "Hathor", "Jael", "Catania"};

            return locations[rand.Next(locations.Length)];
        }

        public static List<Character> GenerateMultipleCharacters(int count)
        {
            var list = new List<Character>();
            for (int i = 1; i <= count; i++)
            {
                list.Add(GenerateRandomCharacter(i));
            }
            return list;
        }
    }
}
